name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm install
    - run: npm run lint
    - run: cp .env.test .env
    - run: docker compose up -d
    - run: npm run test:coverage
    - uses: codecov/codecov-action@v3