name: Publish on release

on:
  release:
    types: [created]

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm run lint
    - run: cp .env.test .env
    - run: docker compose up -d
    - run: npm run test
    - run: npm run build
    - run: npm publish